modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/Mrbysco/DimensionalItemGate/issues"
license="MIT"

[[mods]]
modId="dimensional_itemgate"
version="${file.jarVersion}"
displayName="Dimensional ItemGate"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dimensional-itemgate"
authors="Mrbysco, ShyNieke"
description='''
You can't bring <Netherite Hoe> to this dimension!
'''
[[dependencies.dimensional_itemgate]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.4,1.21)"
ordering="NONE"
side="BOTH"