modLoader="javafml"
loaderVersion="[43,)"
license="MIT"

[[mods]]
modId="dimensional_itemgate"
version="${file.jarVersion}"
displayName="Dimensional ItemGate"
authors="Mrbysco, ShyNieke"
description='''
You can't bring <Netherite Hoe> to this dimension!
'''
[[dependencies.dimensional_itemgate]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,)"
ordering="NONE"
side="BOTH"